/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'HarryG1' at '19/01/17 19:42' with Gradle 2.4
 *
 * @author HarryG1, @date 19/01/17 19:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
